fixes https://github.com/PyBites-Open-Source/pybitesbooks/issues/61
PyBites-Open-Source/pybitesbooks pull request #75
Opened 2023-06-06 14:55 UTC by bbelderbos

2023-06-06 16:22 UTC, bbelderbos commented
Wrote a manage.py command (not included) to reproduce the issue - bug:

<img width="1320" alt="Screenshot 2023-06-06 at 16 05 17" src="https://github.com/PyBites-Open-Source/pybitesbooks/assets/387927/aa25cf08-9a9c-4812-97a8-d09047d594b6">

Now with this code + same data:

<img width="1203" alt="Screenshot 2023-06-06 at 16 27 28" src="https://github.com/PyBites-Open-Source/pybitesbooks/assets/387927/a62471d2-1d09-4c0f-ac49-1c1c8202912b">

Adding a few more pomodori to test the "meet goal" scenario:

<img width="1243" alt="Screenshot 2023-06-06 at 16 29 33" src="https://github.com/PyBites-Open-Source/pybitesbooks/assets/387927/6616adc4-7783-4271-9154-bddb2713a0b8">

TODO: add a pytest ...

2023-06-07 06:46 UTC, bbelderbos commented
@greywidget correct, I wanted to git ignore more patterns. No rush, this feature is totally isolated and not critical and not often used. I did it more as an exercise, as well as working more with pytest-django. Thanks.

2023-06-07 16:38 UTC, greywidget requested changes
- pomo_minutes needs to be passed from view or omitted from template
- Not certain if the intention was to remove the text against each pomo e.g
 `(7 pomodori / 2.92 hours read)`

2023-06-07 16:38 UTC, greywidget commented on pomodoro/views.py
> +    return render(request, 'pomodoro/pomodoro.html', context)
I think pomo_minutes is still required

2023-06-07 16:38 UTC, greywidget commented on tests/test_pomodoro.py
tests look OK to me, all passing

2023-06-08 09:37 UTC, bbelderbos commented on .gitignore
I even made an alias :)

```
$ alias gitign
gitign='curl -s https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore > .gitignore'
```

2023-06-08 09:38 UTC, bbelderbos commented on myreadinglist/templatetags/tags.py
> +    return value.replace("-", " ")
Opened issue.

2023-06-08 09:39 UTC, bbelderbos commented on myreadinglist/test_settings.py
Realized on code clinic that was a missed opportunity here, then Ryan shared his settings, no brainer :)

2023-06-08 09:41 UTC, bbelderbos commented on pomodoro/templates/pomodoro/pomodoro.html
I don't like that Django templates fail silently. pomo_minutes is only in the template, not passed in indeed, will fix

2023-06-08 09:42 UTC, bbelderbos commented on pomodoro/templates/pomodoro/pomodoro.html
> -              <strong>{{ min_read }}</strong> hours read)</small>
I realized this later, I can put it back, I think it's nice. What do you think? Put back or drop?

2023-06-08 09:42 UTC, bbelderbos commented on tests/test_pomodoro.py
ChatGPT helped a lot with this :)

Thanks for reviewing!

2023-06-08 09:46 UTC, bbelderbos commented
> @bbelderbos If we do want to keep the text we could append hours to the `week_stats` in `views.py`:
> 
> * add `DEFAULT_POMO_MIN` back to the imports
> 
> ```
>     week_stats = Counter(pomo.week for pomo in pomodori)
>     # Add in hours read
>     week_stats = [
>         (week, count, round((count * DEFAULT_POMO_MIN) / 60, 2))
>         for week, count in week_stats.items()
>     ]
> 
>     context = {
>         "week_stats": sorted(week_stats, reverse=True),
>         "week_goal": DEFAULT_POMO_GOAL,
>     }
>     return render(request, "pomodoro/pomodoro.html", context)
> ```
> 
> And in the template:
> 
> ```
>     <tbody>
>         {% for week, pomodori, hours_read in week_stats %}
>         <tr>
>           <td>{{ week }} | {% if pomodori >= week_goal %}😄{% else %}😭{% endif %}</td>
>           <td>
>             {% filter multiply:pomodori %}
>               🍅
>             {% endfilter %}
>             {% with week_goal|subtract:pomodori as left %}
>               {% filter multiply:left %}
>                 📖
>               {% endfilter %}
>             {% endwith %}
>             <small>(<strong>{{ pomodori }}</strong> pomodori / 
>               <strong>{{ hours_read }}</strong> hours read)</small>
>           </td>
>         </tr>
>         {% endfor %}
>     </tbody>
> ```
> 
> But I don't feel strongly about it - the graphic alone, without text is nice and clean.
> 
> By the way, I meant to say - the pomodoro `views.py` is much cleaner now, good job

Thank you! Yeah maybe we just leave it icons only, it's clean and shows most importantly if you've hit the goal.

2023-06-08 09:50 UTC, bbelderbos commented on pomodoro/templates/pomodoro/pomodoro.html
https://github.com/PyBites-Open-Source/pybitesbooks/pull/75/commits/99455fd3712d47e71f550c6fd10ae843fe4692b0

2023-06-08 09:50 UTC, bbelderbos commented on pomodoro/templates/pomodoro/pomodoro.html
> -              <strong>{{ min_read }}</strong> hours read)</small>
Keep dropped then.

2023-06-08 09:50 UTC, merged

2023-06-08 09:57 UTC, greywidget commented on pomodoro/migrations/0002_alter_pomodoro_end.py
Ha, I should have realised this - I hit the same thing in my testing, had to create then update the Pomodori